server:
  port: 8160
  contextPath: /geosamples
spring:
  data:
    rest:
      basePath: /geosamples
      defaultPageSize: 25
  datasource:
    url: <oracle connection string>
    username: <username>
    password: <password>
  jpa:
    properties:
      hibernate:
        default_schema: <default schema>
        dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO